### PR TITLE
Build wheels with numpy 2.0rc1 and fix scipy 1.13.0 compatibility

### PR DESCRIPTION
**Pull request by djhoese**
The numpy 2 api is stable now.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
Here's the differences in packages during an upgrade that let me reproduce the test failures locally:

<details>

```
  - alsa-lib                               1.2.10  hd590300_0               conda-forge     Cached
  + alsa-lib                               1.2.11  hd590300_1               conda-forge      555kB
  - aom                                     3.8.1  h59595ed_0               conda-forge     Cached
  + aom                                     3.8.2  h59595ed_0               conda-forge        3MB
  - aws-c-common                           0.9.12  hd590300_0               conda-forge     Cached
  + aws-c-common                           0.9.15  hd590300_0               conda-forge      227kB
  - s2n                                     1.4.3  h06160fa_0               conda-forge     Cached
  + s2n                                     1.4.9  h06160fa_0               conda-forge      341kB
  - libcurl                                 8.5.0  hca28451_0               conda-forge     Cached
  + libcurl                                 8.7.1  hca28451_0               conda-forge     Cached
  - snappy                                 1.1.10  h9fff704_0               conda-forge     Cached
  + snappy                                  1.2.0  hdb0a2a9_1               conda-forge     Cached
  - bottleneck                              1.3.7  py312hc7c0aa3_1          conda-forge     Cached
  + bottleneck                              1.3.8  py312hc7c0aa3_0          conda-forge      140kB
  - c-ares                                 1.26.0  hd590300_0               conda-forge     Cached
  + c-ares                                 1.28.1  hd590300_0               conda-forge     Cached
  - c-blosc2                               2.13.2  hb4ffafa_0               conda-forge     Cached
  + c-blosc2                               2.14.4  hb4ffafa_1               conda-forge      337kB
  - contourpy                               1.2.0  py312h8572e83_0          conda-forge     Cached
  + contourpy                               1.2.1  py312h8572e83_0          conda-forge     Cached
  - coverage                                7.4.1  py312h98912ed_0          conda-forge     Cached
  + coverage                                7.4.4  py312h98912ed_0          conda-forge      357kB
  - jasper                                  4.2.0  he6dfbbe_0               conda-forge     Cached
  + jasper                                  4.2.3  he6dfbbe_0               conda-forge      675kB
  - libaec                                  1.1.2  h59595ed_1               conda-forge     Cached
  + libaec                                  1.1.3  h59595ed_0               conda-forge     Cached
  - libpng                                 1.6.42  h2797004_0               conda-forge     Cached
  + libpng                                 1.6.43  h2797004_0               conda-forge     Cached
  - libexpat                                2.5.0  hcb278e6_1               conda-forge     Cached
  + libexpat                                2.6.2  h59595ed_0               conda-forge     Cached
  - fonttools                              4.49.0  py312h98912ed_0          conda-forge     Cached
  + fonttools                              4.51.0  py312h98912ed_0          conda-forge        3MB
  - libdeflate                               1.19  hd590300_0               conda-forge     Cached
  + libdeflate                               1.20  hd590300_0               conda-forge     Cached
  - libsqlite                              3.45.1  h2797004_0               conda-forge     Cached
  + libsqlite                              3.45.2  h2797004_0               conda-forge     Cached
  - pcre2                                   10.42  hcad00b1_0               conda-forge     Cached
  + pcre2                                   10.43  hcad00b1_0               conda-forge     Cached
  - giflib                                  5.2.1  h0b41bf4_3               conda-forge     Cached
  + giflib                                  5.2.2  hd590300_0               conda-forge       77kB
  - glog                                    0.6.0  h6f12383_0               conda-forge     Cached
  + glog                                    0.7.0  hed5481d_0               conda-forge     Cached
  - xorg-libx11                             1.8.7  h8ee46fc_0               conda-forge     Cached
  + xorg-libx11                             1.8.9  h8ee46fc_0               conda-forge     Cached
  - h5py                                   3.10.0  nompi_py312h1b477d7_101  conda-forge     Cached
  + h5py                                   3.11.0  nompi_py312h1b477d7_100  conda-forge        1MB
  - libabseil                          20230802.1  cxx17_h59595ed_0         conda-forge     Cached
  + libabseil                          20240116.1  cxx17_h59595ed_2         conda-forge     Cached
  - svt-av1                                 1.8.0  h59595ed_0               conda-forge     Cached
  + svt-av1                                 2.0.0  h59595ed_0               conda-forge        3MB
  - libopenblas                            0.3.26  pthreads_h413a1c8_0      conda-forge     Cached
  + libopenblas                            0.3.27  pthreads_h413a1c8_0      conda-forge     Cached
  - libnuma                                2.0.16  h0b41bf4_1               conda-forge     Cached
  + libnuma                                2.0.18  hd590300_0               conda-forge       43kB
  - libxml2                                2.12.5  h232c23b_0               conda-forge     Cached
  + libxml2                                2.12.6  h232c23b_1               conda-forge     Cached
  - minizip                                 4.0.4  h0ab5242_0               conda-forge     Cached
  + minizip                                 4.0.5  h0ab5242_0               conda-forge     Cached
  - mpg123                                 1.32.4  h59595ed_0               conda-forge     Cached
  + mpg123                                 1.32.6  h59595ed_0               conda-forge      492kB
  - mysql-common                           8.0.33  hf1915f5_6               conda-forge     Cached
  + mysql-common                            8.3.0  hf1915f5_4               conda-forge      785kB
  - ncurses                                   6.4  h59595ed_2               conda-forge     Cached
  + ncurses                          6.4.20240210  h59595ed_0               conda-forge     Cached
  - numba                                  0.59.0  py312hacefee8_1          conda-forge     Cached
  + numba                                  0.59.1  py312hacefee8_0          conda-forge        6MB
  - pandoc                               3.1.12.1  ha770c72_0               conda-forge     Cached
  + pandoc                                 3.1.13  ha770c72_0               conda-forge       21MB
  - pyerfa                                2.0.1.1  py312hc7c0aa3_0          conda-forge     Cached
  + pyerfa                                2.0.1.2  py312hc7c0aa3_0          conda-forge      375kB
  - rdma-core                                50.0  hd3aeb46_0               conda-forge     Cached
  + rdma-core                                51.0  hd3aeb46_0               conda-forge     Cached
  - aws-c-compression                      0.2.17  h572eabf_8               conda-forge     Cached
  + aws-c-compression                      0.2.18  hce8ee76_3               conda-forge       19kB
  - aws-checksums                          0.1.17  h572eabf_7               conda-forge     Cached
  + aws-checksums                          0.1.18  hce8ee76_3               conda-forge       50kB
  - aws-c-sdkutils                         0.1.14  h572eabf_0               conda-forge     Cached
  + aws-c-sdkutils                         0.1.15  hce8ee76_3               conda-forge       55kB
  - aws-c-cal                               0.6.9  h14ec70c_3               conda-forge     Cached
  + aws-c-cal                              0.6.11  heb1d5e4_0               conda-forge       46kB
  - cfitsio                                 4.3.1  hbdc6101_0               conda-forge     Cached
  + cfitsio                                 4.4.0  hbdc6101_0               conda-forge     Cached
  - azure-core-cpp                         1.10.3  h91d86a7_1               conda-forge     Cached
  + azure-core-cpp                         1.11.1  h91d86a7_1               conda-forge     Cached
  - eccodes                                2.34.0  he84ddb8_0               conda-forge     Cached
  + eccodes                                2.35.0  he84ddb8_0               conda-forge        4MB
  - expat                                   2.5.0  hcb278e6_1               conda-forge     Cached
  + expat                                   2.6.2  h59595ed_0               conda-forge     Cached
  - libre2-11                          2023.06.02  h7a70373_0               conda-forge     Cached
  + libre2-11                          2023.09.01  h5a48ba9_2               conda-forge     Cached
  - libprotobuf                            4.25.1  hf27288f_1               conda-forge     Cached
  + libprotobuf                            4.25.3  h08a7969_0               conda-forge     Cached
  - libxkbcommon                            1.6.0  hd429924_1               conda-forge     Cached
  + libxkbcommon                            1.7.0  h662e7e4_0               conda-forge      594kB
  - mysql-libs                             8.0.33  hca2cd23_6               conda-forge     Cached
  + mysql-libs                              8.3.0  hca2cd23_4               conda-forge        2MB
  - sqlite                                 3.45.1  h2c6b66d_0               conda-forge     Cached
  + sqlite                                 3.45.2  h2c6b66d_0               conda-forge     Cached
  - aws-c-io                               0.14.3  h3c8c088_1               conda-forge     Cached
  + aws-c-io                               0.14.7  h76a7424_3               conda-forge      158kB
  - python-eccodes                          1.6.1  py312hc7c0aa3_1          conda-forge     Cached
  + python-eccodes                          1.7.0  py312hc7c0aa3_1          conda-forge      103kB
  - gettext                                0.21.1  h27087fc_0               conda-forge     Cached
  + gettext                                0.22.5  h59595ed_2               conda-forge      475kB
  - re2                                2023.06.02  h2873b5e_0               conda-forge     Cached
  + re2                                2023.09.01  h7f4b329_2               conda-forge     Cached
  - orc                                     1.9.2  h7829240_1               conda-forge     Cached
  + orc                                     2.0.0  h17fec99_1               conda-forge        1MB
  - openjpeg                                2.5.0  h488ebb8_3               conda-forge     Cached
  + openjpeg                                2.5.2  h488ebb8_0               conda-forge     Cached
  - libclang13                             15.0.7  default_ha2b6cf4_4       conda-forge     Cached
  + libclang13                             18.1.3  default_h5d6823c_0       conda-forge       11MB
  - aws-c-event-stream                      0.4.1  h17cd1f3_5               conda-forge     Cached
  + aws-c-event-stream                      0.4.2  h01f5eca_8               conda-forge       54kB
  - aws-c-http                              0.8.0  hc6da83f_5               conda-forge     Cached
  + aws-c-http                              0.8.1  hdb68c23_10              conda-forge      195kB
  - libgpg-error                             1.47  h71f35ed_0               conda-forge     Cached
  + libgpg-error                             1.48  h71f35ed_0               conda-forge      266kB
  - libglib                                2.78.4  h783c2da_0               conda-forge     Cached
  + libglib                                2.80.0  hf2295e7_4               conda-forge     Cached
  - libgrpc                                1.60.1  h74775cd_0               conda-forge     Cached
  + libgrpc                                1.62.1  h15f2491_0               conda-forge     Cached
  - scipy                                  1.12.0  py312heda63a1_2          conda-forge     Cached
  + scipy                                  1.13.0  py312heda63a1_0          conda-forge     Cached
  - pillow                                 10.2.0  py312hf3581a9_0          conda-forge     Cached
  + pillow                                 10.3.0  py312hdcec9eb_0          conda-forge     Cached
  - libclang                               15.0.7  default_hb11cfb5_4       conda-forge     Cached
  + libclang                               18.1.3  default_h127d8a8_0       conda-forge       23kB
  - aws-c-mqtt                             0.10.1  h0ef3971_3               conda-forge     Cached
  + aws-c-mqtt                             0.10.3  h50844eb_4               conda-forge      164kB
  - aws-c-auth                             0.7.15  h70caa3e_0               conda-forge     Cached
  + aws-c-auth                             0.7.17  he0b1f16_2               conda-forge      104kB
  - pulseaudio-client                        16.1  hb77b528_5               conda-forge     Cached
  + pulseaudio-client                        17.0  hb77b528_0               conda-forge      758kB
  - glib-tools                             2.78.4  hfc55251_0               conda-forge     Cached
  + glib-tools                             2.80.0  hde27a5a_4               conda-forge      113kB
  - poppler                               24.02.0  h590f24d_0               conda-forge     Cached
  + poppler                               24.03.0  h590f24d_0               conda-forge     Cached
  - libgoogle-cloud                        2.12.0  hef10d8f_5               conda-forge     Cached
  + libgoogle-cloud                        2.22.0  h9be4e54_1               conda-forge     Cached
  - aws-c-s3                                0.5.0  h1b46bed_2               conda-forge     Cached
  + aws-c-s3                                0.5.7  hb7bd14b_1               conda-forge      108kB
  - glib                                   2.78.4  hfc55251_0               conda-forge     Cached
  + glib                                   2.80.0  hf2295e7_4               conda-forge      504kB
  - aws-crt-cpp                            0.26.1  h33f84b2_9               conda-forge     Cached
  + aws-crt-cpp                            0.26.6  hf567797_4               conda-forge      335kB
  - gstreamer                              1.22.9  h98fc4e7_0               conda-forge     Cached
  + gstreamer                              1.24.1  h98fc4e7_1               conda-forge        2MB
  - aws-sdk-cpp                          1.11.242  h65f022c_0               conda-forge     Cached
  + aws-sdk-cpp                          1.11.267  hbf3e495_6               conda-forge        4MB
  - gst-plugins-base                       1.22.9  h8e1006c_0               conda-forge     Cached
  + gst-plugins-base                       1.24.1  hfa15dee_1               conda-forge        3MB
  - tiledb                                 2.20.0  h4386cac_0               conda-forge     Cached
  + tiledb                                 2.21.2  h8a5282e_1               conda-forge        4MB
  - libarrow                               15.0.0  he2c5238_2_cpu           conda-forge     Cached
  + libarrow                               15.0.2  he70291f_3_cpu           conda-forge        8MB
  - libarrow-acero                         15.0.0  h59595ed_2_cpu           conda-forge     Cached
  + libarrow-acero                         15.0.2  hac33072_3_cpu           conda-forge      598kB
  - libarrow-flight                        15.0.0  hdc44a87_2_cpu           conda-forge     Cached
  + libarrow-flight                        15.0.2  hd42f311_3_cpu           conda-forge      506kB
  - libarrow-gandiva                       15.0.0  hacb8726_2_cpu           conda-forge     Cached
  + libarrow-gandiva                       15.0.2  hd4ab825_3_cpu           conda-forge      896kB
  - libparquet                             15.0.0  h352af49_2_cpu           conda-forge     Cached
  + libparquet                             15.0.2  h6a7eafb_3_cpu           conda-forge        1MB
  - libarrow-flight-sql                    15.0.0  hfbc7f12_2_cpu           conda-forge     Cached
  + libarrow-flight-sql                    15.0.2  h9241762_3_cpu           conda-forge      195kB
  - libarrow-dataset                       15.0.0  h59595ed_2_cpu           conda-forge     Cached
  + libarrow-dataset                       15.0.2  hac33072_3_cpu           conda-forge      586kB
  - libarrow-substrait                     15.0.0  hfbc7f12_2_cpu           conda-forge     Cached
  + libarrow-substrait                     15.0.2  h9241762_3_cpu           conda-forge      519kB
  - pyarrow                                15.0.0  py312h176e3d2_2_cpu      conda-forge     Cached
  + pyarrow                                15.0.2  py312h3340c41_3_cpu      conda-forge        5MB
  - astropy-iers-data         0.2024.2.19.0.28.47  pyhd8ed1ab_0             conda-forge     Cached
  + astropy-iers-data           0.2024.4.8.0.32.4  pyhd8ed1ab_0             conda-forge        1MB
  - colorcet                                3.0.1  pyhd8ed1ab_0             conda-forge     Cached
  + colorcet                                3.1.0  pyhd8ed1ab_0             conda-forge      174kB
  - filelock                               3.13.1  pyhd8ed1ab_0             conda-forge     Cached
  + filelock                               3.13.4  pyhd8ed1ab_0             conda-forge       16kB
  - fsspec                               2024.2.0  pyhca7485f_0             conda-forge     Cached
  + fsspec                               2024.3.1  pyhca7485f_0             conda-forge     Cached
  - importlib-metadata                      7.0.1  pyha770c72_0             conda-forge     Cached
  + importlib-metadata                      7.1.0  pyha770c72_0             conda-forge     Cached
  - importlib_resources                     6.1.1  pyhd8ed1ab_0             conda-forge     Cached
  + importlib_resources                     6.4.0  pyhd8ed1ab_0             conda-forge       33kB
  - json5                                  0.9.14  pyhd8ed1ab_0             conda-forge     Cached
  + json5                                  0.9.24  pyhd8ed1ab_0             conda-forge       28kB
  - packaging                                23.2  pyhd8ed1ab_0             conda-forge     Cached
  + packaging                                24.0  pyhd8ed1ab_0             conda-forge     Cached
  - param                                   2.0.2  pyhca7485f_0             conda-forge     Cached
  + param                                   2.1.0  pyhca7485f_0             conda-forge      103kB
  - parso                                   0.8.3  pyhd8ed1ab_0             conda-forge     Cached
  + parso                                   0.8.4  pyhd8ed1ab_0             conda-forge     Cached
  - pycparser                                2.21  pyhd8ed1ab_0             conda-forge     Cached
  + pycparser                                2.22  pyhd8ed1ab_0             conda-forge      105kB
  - pyparsing                               3.1.1  pyhd8ed1ab_0             conda-forge     Cached
  + pyparsing                               3.1.2  pyhd8ed1ab_0             conda-forge     Cached
  - python-dateutil                         2.8.2  pyhd8ed1ab_0             conda-forge     Cached
  + python-dateutil                         2.9.0  pyhd8ed1ab_0             conda-forge     Cached
  - referencing                            0.33.0  pyhd8ed1ab_0             conda-forge     Cached
  + referencing                            0.34.0  pyhd8ed1ab_0             conda-forge       42kB
  - send2trash                              1.8.2  pyh41d4057_0             conda-forge     Cached
  + send2trash                              1.8.3  pyh0d859eb_0             conda-forge       23kB
  - setuptools                             69.1.0  pyhd8ed1ab_0             conda-forge     Cached
  + setuptools                             69.2.0  pyhd8ed1ab_0             conda-forge     Cached
  - skyfield                                 1.45  pyh1a96a4e_0             conda-forge     Cached
  + skyfield                                 1.48  pyhca7485f_0             conda-forge      377kB
  - sniffio                                 1.3.0  pyhd8ed1ab_0             conda-forge     Cached
  + sniffio                                 1.3.1  pyhd8ed1ab_0             conda-forge       15kB
  - terminado                              0.18.0  pyh0d859eb_0             conda-forge     Cached
  + terminado                              0.18.1  pyh0d859eb_0             conda-forge       22kB
  - traitlets                              5.14.1  pyhd8ed1ab_0             conda-forge     Cached
  + traitlets                              5.14.2  pyhd8ed1ab_0             conda-forge     Cached
  - types-python-dateutil         2.8.19.20240106  pyhd8ed1ab_0             conda-forge     Cached
  + types-python-dateutil          2.9.0.20240316  pyhd8ed1ab_0             conda-forge       22kB
  - typing_extensions                       4.9.0  pyha770c72_0             conda-forge     Cached
  + typing_extensions                      4.11.0  pyha770c72_0             conda-forge     Cached
  - urllib3                               1.26.18  pyhd8ed1ab_0             conda-forge     Cached
  + urllib3                                 2.0.7  pyhd8ed1ab_0             conda-forge       99kB
  - wheel                                  0.42.0  pyhd8ed1ab_0             conda-forge     Cached
  + wheel                                  0.43.0  pyhd8ed1ab_1             conda-forge     Cached
  - xyzservices                         2023.10.1  pyhd8ed1ab_0             conda-forge     Cached
  + xyzservices                          2024.4.0  pyhd8ed1ab_0             conda-forge     Cached
  - zarr                                   2.17.0  pyhd8ed1ab_0             conda-forge     Cached
  + zarr                                   2.17.2  pyhd8ed1ab_0             conda-forge     Cached
  - virtualenv                            20.25.0  pyhd8ed1ab_0             conda-forge     Cached
  + virtualenv                            20.25.1  pyhd8ed1ab_0             conda-forge        3MB
  - markdown                                3.5.2  pyhd8ed1ab_0             conda-forge     Cached
  + markdown                                  3.6  pyhd8ed1ab_0             conda-forge       78kB
  - importlib_metadata                      7.0.1  hd8ed1ab_0               conda-forge     Cached
  + importlib_metadata                      7.1.0  hd8ed1ab_0               conda-forge     Cached
  - pooch                                   1.8.0  pyhd8ed1ab_0             conda-forge     Cached
  + pooch                                   1.8.1  pyhd8ed1ab_0             conda-forge     Cached
  - pyviz_comms                             3.0.0  pyhd8ed1ab_0             conda-forge     Cached
  + pyviz_comms                             3.0.1  pyhd8ed1ab_0             conda-forge       48kB
  - httpcore                                1.0.3  pyhd8ed1ab_0             conda-forge     Cached
  + httpcore                                1.0.5  pyhd8ed1ab_0             conda-forge       46kB
  - jupyter_server_terminals                0.5.2  pyhd8ed1ab_0             conda-forge     Cached
  + jupyter_server_terminals                0.5.3  pyhd8ed1ab_0             conda-forge       20kB
  - jupyter_events                          0.9.0  pyhd8ed1ab_0             conda-forge     Cached
  + jupyter_events                         0.10.0  pyhd8ed1ab_0             conda-forge       21kB
  - comm                                    0.2.1  pyhd8ed1ab_0             conda-forge     Cached
  + comm                                    0.2.2  pyhd8ed1ab_0             conda-forge       12kB
  - typing-extensions                       4.9.0  hd8ed1ab_0               conda-forge     Cached
  + typing-extensions                      4.11.0  hd8ed1ab_0               conda-forge       10kB
  - ipython                                8.21.0  pyh707e725_0             conda-forge     Cached
  + ipython                                8.22.2  pyh707e725_0             conda-forge     Cached
  - botocore                              1.34.34  pyhd8ed1ab_0             conda-forge     Cached
  + botocore                              1.34.51  pyge310_1234567_0        conda-forge        7MB
  - pre-commit                              3.6.2  pyha770c72_0             conda-forge     Cached
  + pre-commit                              3.7.0  pyha770c72_0             conda-forge      181kB
  - dask-core                            2024.2.0  pyhd8ed1ab_0             conda-forge     Cached
  + dask-core                            2024.4.1  pyhd8ed1ab_0             conda-forge     Cached
  - pytest-cov                              4.1.0  pyhd8ed1ab_0             conda-forge     Cached
  + pytest-cov                              5.0.0  pyhd8ed1ab_0             conda-forge       26kB
  - httpx                                  0.26.0  pyhd8ed1ab_0             conda-forge     Cached
  + httpx                                  0.27.0  pyhd8ed1ab_0             conda-forge       65kB
  - aiobotocore                            2.11.2  pyhd8ed1ab_0             conda-forge     Cached
  + aiobotocore                            2.12.2  pyhd8ed1ab_0             conda-forge       67kB
  - distributed                          2024.2.0  pyhd8ed1ab_0             conda-forge     Cached
  + distributed                          2024.4.1  pyhd8ed1ab_0             conda-forge     Cached
  - s3fs                                 2024.2.0  pyhd8ed1ab_0             conda-forge     Cached
  + s3fs                                 2024.3.1  pyhd8ed1ab_0             conda-forge       32kB
  - astropy                                 6.0.0  py312hc7c0aa3_0          conda-forge     Cached
  + astropy                                 6.0.1  py312hc7c0aa3_0          conda-forge        9MB
  - pandas                                  2.2.0  py312hfb8ada1_0          conda-forge     Cached
  + pandas                                  2.2.2  py312hfb8ada1_0          conda-forge       15MB
  - matplotlib-base                         3.8.3  py312he5832f3_0          conda-forge     Cached
  + matplotlib-base                         3.8.4  py312he5832f3_0          conda-forge        8MB
  - jupyter_core                            5.7.1  py312h7900ff3_0          conda-forge     Cached
  + jupyter_core                            5.7.2  py312h7900ff3_0          conda-forge       93kB
  - matplotlib                              3.8.3  py312h7900ff3_0          conda-forge     Cached
  + matplotlib                              3.8.4  py312h7900ff3_0          conda-forge        8kB
  - cartopy                                0.22.0  py312hfb8ada1_1          conda-forge     Cached
  + cartopy                                0.23.0  py312hfb8ada1_0          conda-forge        2MB
  - xarray                               2024.2.0  pyhd8ed1ab_0             conda-forge     Cached
  + xarray                               2024.3.0  pyhd8ed1ab_0             conda-forge     Cached
  - bokeh                                   3.3.4  pyhd8ed1ab_0             conda-forge     Cached
  + bokeh                                   3.4.1  pyhd8ed1ab_0             conda-forge        5MB
  - nbformat                                5.9.2  pyhd8ed1ab_0             conda-forge     Cached
  + nbformat                               5.10.4  pyhd8ed1ab_0             conda-forge      101kB
  - jupyter_client                          8.6.0  pyhd8ed1ab_0             conda-forge     Cached
  + jupyter_client                          8.6.1  pyhd8ed1ab_0             conda-forge      106kB
  - rioxarray                              0.15.1  pyhd8ed1ab_0             conda-forge     Cached
  + rioxarray                              0.15.3  pyhd8ed1ab_0             conda-forge       51kB
  - panel                                   1.3.8  pyhd8ed1ab_0             conda-forge     Cached
  + panel                                   1.4.1  pyhd8ed1ab_0             conda-forge       19MB
  - dask                                 2024.2.0  pyhd8ed1ab_0             conda-forge     Cached
  + dask                                 2024.4.1  pyhd8ed1ab_0             conda-forge     Cached
  - nbclient                                0.8.0  pyhd8ed1ab_0             conda-forge     Cached
  + nbclient                               0.10.0  pyhd8ed1ab_0             conda-forge       28kB
  - ipykernel                              6.29.2  pyhd33586a_0             conda-forge     Cached
  + ipykernel                              6.29.3  pyhd33586a_0             conda-forge      119kB
  - geoviews-core                          1.11.1  pyha770c72_0             conda-forge     Cached
  + geoviews-core                          1.12.0  pyha770c72_0             conda-forge      399kB
  - nbconvert-core                         7.16.1  pyhd8ed1ab_0             conda-forge     Cached
  + nbconvert-core                         7.16.3  pyhd8ed1ab_1             conda-forge      189kB
  - geoviews                               1.11.1  pyhd8ed1ab_0             conda-forge     Cached
  + geoviews                               1.12.0  pyhd8ed1ab_0             conda-forge        8kB
  - nbconvert-pandoc                       7.16.1  pyhd8ed1ab_0             conda-forge     Cached
  + nbconvert-pandoc                       7.16.3  hd8ed1ab_1               conda-forge        8kB
  - jupyter_server                         2.12.5  pyhd8ed1ab_0             conda-forge     Cached
  + jupyter_server                         2.14.0  pyhd8ed1ab_0             conda-forge      325kB
  - nbconvert                              7.16.1  pyhd8ed1ab_0             conda-forge     Cached
  + nbconvert                              7.16.3  hd8ed1ab_1               conda-forge        8kB
  - jupyterlab_server                      2.25.3  pyhd8ed1ab_0             conda-forge     Cached
  + jupyterlab_server                      2.26.0  pyhd8ed1ab_0             conda-forge       49kB
  - jupyter-lsp                             2.2.2  pyhd8ed1ab_0             conda-forge     Cached
  + jupyter-lsp                             2.2.5  pyhd8ed1ab_0             conda-forge       56kB
  - jupyterlab                              4.1.1  pyhd8ed1ab_0             conda-forge     Cached
  + jupyterlab                              4.1.6  pyhd8ed1ab_0             conda-forge        8MB
  - notebook                                7.1.0  pyhd8ed1ab_0             conda-forge     Cached
  + notebook                                7.1.2  pyhd8ed1ab_0             conda-forge        4MB
```

</details>

**Comment by djhoese** [comment]
Ok it is scipy 1.12.0 going to 1.13.0 that is causing the failures. Now to go down the rabbit hole...

**Comment by djhoese** [comment]
Ok caused by rewrites of the regular grid interpolator here:

https://docs.scipy.org/doc/scipy/release/1.13.0-notes.html#scipy-interpolate-improvements

**Review by mraspaud — APPROVED** [review]
Lgtm, but do we need to worry about the unstable build failing? Thanks for digging into this.

**Pull request merged**
