### PR TITLE
fix this numpy thingy?

### PR DESCRIPTION
**Pull request by ngam**
- [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by ngam** [comment]
xref https://github.com/conda-forge/python-geotiepoints-feedstock/pull/21

**Comment by djhoese** [comment]
This usage is here for a reason. Unless numpy has changed something about their packaging this `oldest-supported-numpy` ensures that we build wheels against the oldest supported numpy for a particular version of Python. Without this, users installing wheels built with newer numpy would not be able to use the package in environments with older versions of numpy installed.

**Comment by ngam** [comment]
> 

Ok makes sense. I honestly have no idea. I think things work slightly differently in conda, but I am not sure. We should ask the python people there about this...

**Comment by djhoese** [comment]
Yes. The conda-forge stuff have numpy pinnings. We can try playing with the patch there. I know other packages that use oldest-supported-numpy so I'll have to compare how they do it.

**Pull request closed without merging**
